title: Quanser Aero 2
description: Portafolio del proyecto de Control Avanzado y Robótica O26 - Control LQR y Observador de Estados sobre el Quanser Aero 2

# GitHub Pages: modo recomendado
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# IMPORTANTES:
# - Para GitHub Pages (Project Page), edita:
#     url: "https://sebastiux.github.io"
#     baseurl: "/NOMBRE_DEL_REPO"
url: "https://sebastiux.github.io"
baseurl: "/reportequanseravanzado"

#Configuracion Formato, Header y Footer
just_the_docs:
  # incluir CSS adicional
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

search_enabled: true
search:
  # Cambia el numero dependiendo el numero de subniveles de páginas, poner 1 por default
  heading_level: 3

# Ejemplo de enlace auxiliar (aparece arriba a la derecha)
aux_links:
  "Reporte PDF":
    - "/reportequanseravanzado/assets/files/reporte-aero2.pdf"
  "Repositorio en GitHub":
    - "https://github.com/sebastiux/reportequanseravanzado"

# Callouts (bloques de nota/resultado/advertencia)
callouts_level: quiet
callouts:
  note:
    title: Nota
    color: blue
  result:
    title: Resultado
    color: green
  important:
    title: Importante
    color: purple
  warning:
    title: Advertencia
    color: red

# Enlaces
permalink: pretty

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
